backend/models/Users.php
<?php

namespace backend\models;


use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $fio
 * @property string $login
 * @property string $password
 * @property int $role_id
 */
class Users extends ActiveRecord
{
    const USER_STATUS_ACTIVE    = 1;
    const USER_STATUS_IN_ACTIVE = 2;
    const USER_STATUS_BLOCKED   = 3; 
    const USER_STATUS_DELETED   = 4;
    const GENERAL_ADMIN = 1;

    const ROLE_ADMIN = 1;
    const ROLE_MODERATOR = 2;
    const ROLE_USER = 3;


    public $new_password;
    public $image;
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status','role_id'] ,'integer'],
            [['fio', 'login', 'password','phone','email', 'balans', 'date_cr','avatar'], 'string', 'max' => 255],
            [['fio', 'login', 'password', 'status'], 'required'],
            [['login'],  'unique'],
            [['email'],  'email'],
            [['date_cr','image' ,'new_password'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fio' => 'ФИО',
            'login' => 'Логин',
            'password' => 'Пароль',
            'new_password' => 'Новый пароль',
            'status' => 'Статус',
            'phone' => 'Телефон',
            'email' => 'Email',
            'balans' => 'Баланс',
            'date_cr' => 'Дата создания',
            'avatar' => 'Фото',
            'image' => 'Фото',
            'role_id' => 'Роль',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {   
            $user = Yii::$app->user->identity;
            $this->password = Yii::$app->security->generatePasswordHash($this->password);
            $this->date_cr = date('Y-m-d H:i');
        }

        if($this->new_password != null) $this->password = Yii::$app->security->generatePasswordHash($this->new_password);
        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
    }

    public function beforeDelete()
    {
        return parent::beforeDelete();
    }

    public static function getStatus()
    {
        return ArrayHelper::map([
            ['id' => self::USER_STATUS_ACTIVE, 'name' => 'Активный'],
            ['id' => self::USER_STATUS_IN_ACTIVE, 'name' => 'Не активен'],
            ['id' => self::USER_STATUS_BLOCKED, 'name' => 'Блокированный'],
            ['id' => self::USER_STATUS_DELETED, 'name' => 'Удален'],
        ], 'id', 'name');
    }

    public function getStatusDescription()
    {
        switch ($this->status) {
            case 1: return "Активный";
            case 2: return "Не активен";
            case 3: return "Блокированный";
            case 4: return "Удален";
            default: return "Неизвестно";
        }
    }

    public static function getRole()
    {
        return ArrayHelper::map([
            ['id' => self::ROLE_ADMIN, 'name' => 'Администратор'],
            ['id' => self::ROLE_MODERATOR, 'name' => 'Модератор'],
            ['id' => self::ROLE_USER, 'name' => 'Ползователь'],
        ], 'id', 'name');
    }

    public function getRoleDescription()
    {
        switch ($this->role_id) {
            case 1: return "Администратор";
            case 2: return "Модераторн";
            case 3: return "Ползователь";
            default: return "Неизвестно";
        }
    }

    public function uploadAvatar()
    {   
        $fileName = "";
        $fileName = $this->id . '-' . Yii::$app->security->generateRandomString() . '.' . $this->image->extension;
        if(!empty($this->image))
        {   
            if(file_exists('uploads/avatars/'.$this->avatar) && $this->avatar != null)
            {
                unlink('uploads/avatars/'.$this->avatar);
            }

            $this->image->saveAs('uploads/avatars/'.$fileName);
            Yii::$app->db->createCommand()->update('users', ['avatar' => $fileName], [ 'id' => $this->id ])->execute();
        }
    }

    public  function getAvatar()
    {
        if (!file_exists('uploads/avatars/'.$this->avatar) || $this->avatar == '') {
            $path = 'http://' . $_SERVER['SERVER_NAME'].'/admin/img/nouser.png';
        } else {
            $path = 'http://' . $_SERVER['SERVER_NAME'].'/admin/uploads/avatars/'.$this->avatar;
        }
        return $path;
    }
    
}

common/models/User.php
<?php

namespace common\models;
use backend\models\Users;

class User extends Users/*\yii\base\Object*/ implements \yii\web\IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['login' => $username]);
    }

    public function setToken()
    {
        $this->access_token = \Yii::$app->getSecurity()->generateRandomString();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return false;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
       return \Yii::$app->security->validatePassword($password, $this->password);
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Users;
use backend\models\search\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {    
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionProfile()
    {
        $request = Yii::$app->request;
        $model = Users::findOne(Yii::$app->user->identity->id);
        return $this->render('profile', [
            'model' => $model,
        ]);        
    }
    
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Users();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if(isset($model->image )) $model->uploadAvatar();
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
            }else{           
                return [
                    'title'=> "Создать нового пользователя",
                    'size' => "large",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id); 

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if(isset($model->image )) $model->uploadAvatar();
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
                    
            }else{
                 return [
                    'title'=> "Изменить пользователя",
                    'size' => "large",
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        if ($id != 1)$model = Users::findOne($id);
        if(file_exists('uploads/avatars/'.$model->avatar )&&$model->avatar != null)
        {
            unlink('uploads/avatars/'.$model->avatar );
        }

        $model->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
          
            return $this->redirect(['index']);
        }


    }
    
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/users/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use backend\models\Users;
use backend\models\Roles;


return [
    // [
    //     'class' => 'kartik\grid\CheckboxColumn',
    //     'width' => '20px',
    // ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
     [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'avatar',
        'contentOptions' => ['style'=>'width: 48px; height:48px;'],
        'content' => function ($data) {
         return '<center>' . Html::img($data->getAvatar(), [ 'style' => 'height:48px;width:48px; object-fit: cover;']) . '</center>';
           
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fio',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'login',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'filter' => Users::getStatus(),
        'content' => function ($data) {
           return $data->getStatusDescription();
       },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'role_id',
        'filter' => Users::getRole(),
        'content' => function ($data) {
            return $data->getRoleDescription();
        },
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'width'=>'120px',
        'template' => '{leadUpdate} {leadDelete}',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'buttons'=>[
            'leadUpdate' => function ($url, $model) {
                $url = Url::to(['/users/update', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [ 'role'=>'modal-remote', 'data-toggle'=>'tooltip', 'title'=>'Редактировать','class'=>'btn btn-primary btn-xs']);
            },
            'leadDelete' => function ($url, $model) {
                if($model->id != 1){
                    $url = Url::to(['/users/delete', 'id' => $model->id]);
                    return Html::a('<span style="font-size: 12px;" class="glyphicon glyphicon-trash"></span>', $url, [
                        'role'=>'modal-remote','title'=>'Удалить','class'=>'btn btn-danger btn-xs' ,
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                        'data-toggle'=>'tooltip',
                        'data-confirm-title'=>'Подтвердите действие',
                        'data-confirm-message'=>'Вы уверены что хотите удалить этого элемент?',
                    ]);
                }
            },
        ],
    ],

];   

backend/views/users/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\Roles;
?>

<div class="users-form">
    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-4">
                <div id="image" class="col-md-12">
                <?=Html::img($model->getAvatar(), [
                    'style' => 'width:150px; height:150px;object-fit: cover;',
                    'class'=>'img-circle',
                ])?>
            </div>
            <br>
            <div class="col-md-12">
               <?= $form->field($model, 'image')->fileInput(['class'=>"image_input",'id'=>'inputFile']); ?>
            </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $model->isNewRecord ? $form->field($model, 'password')->textInput(['maxlength' => true]) : $form->field($model, 'new_password')->textInput(['maxlength' => true]) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
                                      'mask' => '+\9\9899-999-99-99',
                                     'options' => [
                                          'placeholder' => '+998-99-999-99-99',
                                         'class'=>'form-control',
                                     ]
                        ]) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'status')->dropDownList($model->getStatus(), ['prompt' => 'Выберите статус','disabled' => $model->id != 1 ? false : true]) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'role_id')->dropDownList($model->getRole(), ['prompt' => 'Выберите роль','disabled' => $model->id != 1 ? false : true]) ?>
                    </div>
               </div>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>
<?php 
$this->registerJs(<<<JS

$("#inputFile").on('change',function(e){
  var files = e.target.files;
    $.each(files, function(i,file){
        var reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = function(e){
            var template = '<img style="object-fit: cover; width:150px; height:150px;" src="'+e.target.result+'" class="img-circle"> ';
            $('#image').html('');
            $('#image').append(template);
        };
    });
});
JS
);
?>

backend/views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/users/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

$this->title = "Пользователи";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse user-index">
    <div class="panel-heading">
        <div class="panel-heading-btn">
            <a href="/admin/users/create" role="modal-remote" class="btn btn-primary btn-xs"> Добавить <i class="fa fa-plus"></i> </a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
        <h4 class="panel-title">Пользователи</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'tableOptions' => ['class' => 'table table-bordered'],
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>'',
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            '<div class="clearfix"></div>',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

backend/views/users/profile.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

$this->title = "Профиль";
$this->params['breadcrumbs'][] = $this->title;
CrudAsset::register($this);
$session = Yii::$app->session;
?>
 <style type="text/css">
     p {
    margin: 12px 0px -5px;
}
 </style>                       

<?php Pjax::begin(['enablePushState' => false, 'id' => 'crud-datatable-pjax']) ?>
       
    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-7">
                <!-- CONTACT ITEM -->
                <div class="panel panel-default">
                    <div class="panel-body profile">
                        <div class="profile-image">
                             <img src="<?= $model->getAvatar()?>" style=" width:120px; height:120px; object-fit: cover;" alt="Пользователи">
                        </div>
                        <div class="profile-data">
                            <div class="profile-data-name"><?=$model->fio?></div>
                            <div class="profile-data-title"></div>
                        </div>
                        <div class="profile-controls">
                            <a href="#"  data-toggle="" class="profile-control-left" title="Уведомления"><span class="fa fa-bell-o" data-pjax="0"></span></a>
                            <a href="/admin/users/update?id=<?=$model->id?>" data-toggle="" class="profile-control-right" role="modal-remote" title="Изменить"><span class="fa fa-pencil"></span></a>
                        </div>
                    </div>                                
                    <div class="panel-body">                                    
                        <div class="contact-info">
                            <p><b>Логин</b><br><?= $model->login?></p>         
                            <p><b>Телефон</b><br><?= $model->phone?></p>
                            <p><b>Email</b><br><?= $model->email?></p>
                            <p><b>Статус</b><br><?=$model->getStatusDescription()?></p>
                        </div>
                    </div>                                
                </div>
                <!-- END CONTACT ITEM -->
            </div>
    </div>

<?php Pjax::end() ?>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "options" => [
        "tabindex" => false,
    ],
    "footer"=>"",
])?>
<?php Modal::end(); ?>

backend/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
?>
<div class="users-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>